//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Text", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string AboutUs_Header {
            get {
                return ResourceManager.GetString("AboutUs_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Argo Development is a new software development company. We provide full cycle development including business analysis, development, QA and support.&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. &lt;/p&gt;.
        /// </summary>
        internal static string AboutUs_Text {
            get {
                return ResourceManager.GetString("AboutUs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string Button_ContactUs {
            get {
                return ResourceManager.GetString("Button_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire us!.
        /// </summary>
        internal static string Button_HireUs {
            get {
                return ResourceManager.GetString("Button_HireUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@argo.studio.
        /// </summary>
        internal static string Contacts_Email {
            get {
                return ResourceManager.GetString("Contacts_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts_Header {
            get {
                return ResourceManager.GetString("Contacts_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +375 (29) 848 484 84.
        /// </summary>
        internal static string Contacts_Phone {
            get {
                return ResourceManager.GetString("Contacts_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social networks.
        /// </summary>
        internal static string Contacts_SocialNetworksHeader {
            get {
                return ResourceManager.GetString("Contacts_SocialNetworksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface        ///.
        /// </summary>
        internal static string Features_DesignBenefit1 {
            get {
                return ResourceManager.GetString("Features_DesignBenefit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Expirience / Prototyping.
        /// </summary>
        internal static string Features_DesignBenefit2 {
            get {
                return ResourceManager.GetString("Features_DesignBenefit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branding and Identity.
        /// </summary>
        internal static string Features_DesignBenefit3 {
            get {
                return ResourceManager.GetString("Features_DesignBenefit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic design (booklets, banners, etc.).
        /// </summary>
        internal static string Features_DesignBenefit4 {
            get {
                return ResourceManager.GetString("Features_DesignBenefit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string Features_DesignHeader {
            get {
                return ResourceManager.GetString("Features_DesignHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface.
        /// </summary>
        internal static string Features_DevelopmentBenefit1 {
            get {
                return ResourceManager.GetString("Features_DevelopmentBenefit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Expirience / Prototyping.
        /// </summary>
        internal static string Features_DevelopmentBenefit2 {
            get {
                return ResourceManager.GetString("Features_DevelopmentBenefit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branding and Identity.
        /// </summary>
        internal static string Features_DevelopmentBenefit3 {
            get {
                return ResourceManager.GetString("Features_DevelopmentBenefit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Expirience / Prototyping.
        /// </summary>
        internal static string Features_DevelopmentBenefit4 {
            get {
                return ResourceManager.GetString("Features_DevelopmentBenefit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        internal static string Features_DevelopmentHeader {
            get {
                return ResourceManager.GetString("Features_DevelopmentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface.
        /// </summary>
        internal static string Features_QABenefit1 {
            get {
                return ResourceManager.GetString("Features_QABenefit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Expirience / Prototyping.
        /// </summary>
        internal static string Features_QABenefit2 {
            get {
                return ResourceManager.GetString("Features_QABenefit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branding and Identity.
        /// </summary>
        internal static string Features_QABenefit3 {
            get {
                return ResourceManager.GetString("Features_QABenefit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Expirience / Prototyping.
        /// </summary>
        internal static string Features_QABenefit4 {
            get {
                return ResourceManager.GetString("Features_QABenefit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Assurance.
        /// </summary>
        internal static string Features_QAHeader {
            get {
                return ResourceManager.GetString("Features_QAHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argo.studio - All rights reserved.
        /// </summary>
        internal static string Footer_Copyright {
            get {
                return ResourceManager.GetString("Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Development Company.
        /// </summary>
        internal static string Header_LogoLabel {
            get {
                return ResourceManager.GetString("Header_LogoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branding.
        /// </summary>
        internal static string Label_Branding {
            get {
                return ResourceManager.GetString("Label_Branding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        internal static string Label_Development {
            get {
                return ResourceManager.GetString("Label_Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Design.
        /// </summary>
        internal static string Label_GraphicDesign {
            get {
                return ResourceManager.GetString("Label_GraphicDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI / UX Design.
        /// </summary>
        internal static string Label_UIDesign {
            get {
                return ResourceManager.GetString("Label_UIDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Booklets for Belarusian exhibition company.&lt;/p&gt;
        ///&lt;p&gt;Outsource project. Design.&lt;/p&gt;.
        /// </summary>
        internal static string Projects_BelinterexpoDescription {
            get {
                return ResourceManager.GetString("Projects_BelinterexpoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Cargo Club - SaaS platform for logistics and transport companies.&lt;/p&gt;
        ///&lt;p&gt;Outsource project. Full cycle product development.&lt;/p&gt;.
        /// </summary>
        internal static string Projects_CargoDescription {
            get {
                return ResourceManager.GetString("Projects_CargoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See our projects.
        /// </summary>
        internal static string Projects_Header {
            get {
                return ResourceManager.GetString("Projects_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here can be your project!.
        /// </summary>
        internal static string Projects_Proposal {
            get {
                return ResourceManager.GetString("Projects_Proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;VerniMoment description&lt;/p&gt;.
        /// </summary>
        internal static string Projects_VerniMomentDescription {
            get {
                return ResourceManager.GetString("Projects_VerniMomentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We make products that really works!.
        /// </summary>
        internal static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social networks.
        /// </summary>
        internal static string SocialNetworksHeader {
            get {
                return ResourceManager.GetString("SocialNetworksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet our team.
        /// </summary>
        internal static string Team_Header {
            get {
                return ResourceManager.GetString("Team_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi. Datat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.         ///        ///laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Team_Member1Description {
            get {
                return ResourceManager.GetString("Team_Member1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stanislav Brill.
        /// </summary>
        internal static string Team_Member1Name {
            get {
                return ResourceManager.GetString("Team_Member1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office cleaner.
        /// </summary>
        internal static string Team_Member1Position {
            get {
                return ResourceManager.GetString("Team_Member1Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.         ///datat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Team_Member2Description {
            get {
                return ResourceManager.GetString("Team_Member2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artiom Petrykin.
        /// </summary>
        internal static string Team_Member2Name {
            get {
                return ResourceManager.GetString("Team_Member2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI / UX Designer.
        /// </summary>
        internal static string Team_Member2Position {
            get {
                return ResourceManager.GetString("Team_Member2Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi. Datat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Team_Member3Description {
            get {
                return ResourceManager.GetString("Team_Member3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alexander Neznau.
        /// </summary>
        internal static string Team_Member3Name {
            get {
                return ResourceManager.GetString("Team_Member3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        internal static string Team_Member3Position {
            get {
                return ResourceManager.GetString("Team_Member3Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argo.
        /// </summary>
        internal static string Title_Index {
            get {
                return ResourceManager.GetString("Title_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string TopMenu_AboutUs {
            get {
                return ResourceManager.GetString("TopMenu_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string TopMenu_Company {
            get {
                return ResourceManager.GetString("TopMenu_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string TopMenu_Projects {
            get {
                return ResourceManager.GetString("TopMenu_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string TopMenu_Team {
            get {
                return ResourceManager.GetString("TopMenu_Team", resourceCulture);
            }
        }
    }
}
