//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Text", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string AboutUs_Header {
            get {
                return ResourceManager.GetString("AboutUs_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Argo Development is a new outsource software development company. &lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;We specialized on launching SaaS projects, startups. Provide full cycle web and mobile development including Business Analysis, UI and UX Design, Development, Quality Assurance and Support. &lt;/p&gt;.
        /// </summary>
        internal static string AboutUs_Text {
            get {
                return ResourceManager.GetString("AboutUs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string Button_ContactUs {
            get {
                return ResourceManager.GetString("Button_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire us!.
        /// </summary>
        internal static string Button_HireUs {
            get {
                return ResourceManager.GetString("Button_HireUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@argo.team.
        /// </summary>
        internal static string Contacts_Email {
            get {
                return ResourceManager.GetString("Contacts_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts_Header {
            get {
                return ResourceManager.GetString("Contacts_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +375 44 709 79 07.
        /// </summary>
        internal static string Contacts_Phone1 {
            get {
                return ResourceManager.GetString("Contacts_Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +48 530 450 573.
        /// </summary>
        internal static string Contacts_Phone2 {
            get {
                return ResourceManager.GetString("Contacts_Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social networks.
        /// </summary>
        internal static string Contacts_SocialNetworksHeader {
            get {
                return ResourceManager.GetString("Contacts_SocialNetworksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface.
        /// </summary>
        internal static string Features_DesignBenefit1 {
            get {
                return ResourceManager.GetString("Features_DesignBenefit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Expirience / Prototyping.
        /// </summary>
        internal static string Features_DesignBenefit2 {
            get {
                return ResourceManager.GetString("Features_DesignBenefit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branding and Identity.
        /// </summary>
        internal static string Features_DesignBenefit3 {
            get {
                return ResourceManager.GetString("Features_DesignBenefit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic design (booklets, banners, etc.).
        /// </summary>
        internal static string Features_DesignBenefit4 {
            get {
                return ResourceManager.GetString("Features_DesignBenefit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string Features_DesignHeader {
            get {
                return ResourceManager.GetString("Features_DesignHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web (JavaScript, .NET, C#).
        /// </summary>
        internal static string Features_DevelopmentBenefit1 {
            get {
                return ResourceManager.GetString("Features_DevelopmentBenefit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile (C#, Swift, JAVA).
        /// </summary>
        internal static string Features_DevelopmentBenefit2 {
            get {
                return ResourceManager.GetString("Features_DevelopmentBenefit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop (.NET, Swift).
        /// </summary>
        internal static string Features_DevelopmentBenefit3 {
            get {
                return ResourceManager.GetString("Features_DevelopmentBenefit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud (.NET).
        /// </summary>
        internal static string Features_DevelopmentBenefit4 {
            get {
                return ResourceManager.GetString("Features_DevelopmentBenefit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        internal static string Features_DevelopmentHeader {
            get {
                return ResourceManager.GetString("Features_DevelopmentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test strategy writing.
        /// </summary>
        internal static string Features_QABenefit1 {
            get {
                return ResourceManager.GetString("Features_QABenefit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual testing.
        /// </summary>
        internal static string Features_QABenefit2 {
            get {
                return ResourceManager.GetString("Features_QABenefit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation testing (Selenium WD, C#).
        /// </summary>
        internal static string Features_QABenefit3 {
            get {
                return ResourceManager.GetString("Features_QABenefit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit testing.
        /// </summary>
        internal static string Features_QABenefit4 {
            get {
                return ResourceManager.GetString("Features_QABenefit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Assurance.
        /// </summary>
        internal static string Features_QAHeader {
            get {
                return ResourceManager.GetString("Features_QAHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argo.studio - All rights reserved.
        /// </summary>
        internal static string Footer_Copyright {
            get {
                return ResourceManager.GetString("Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Development Company.
        /// </summary>
        internal static string Header_LogoLabel {
            get {
                return ResourceManager.GetString("Header_LogoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branding.
        /// </summary>
        internal static string Label_Branding {
            get {
                return ResourceManager.GetString("Label_Branding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        internal static string Label_Development {
            get {
                return ResourceManager.GetString("Label_Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Design.
        /// </summary>
        internal static string Label_GraphicDesign {
            get {
                return ResourceManager.GetString("Label_GraphicDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal project.
        /// </summary>
        internal static string Label_InternalProject {
            get {
                return ResourceManager.GetString("Label_InternalProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outsource.
        /// </summary>
        internal static string Label_Outsource {
            get {
                return ResourceManager.GetString("Label_Outsource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Assurance.
        /// </summary>
        internal static string Label_QA {
            get {
                return ResourceManager.GetString("Label_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social apps.
        /// </summary>
        internal static string Label_SocialApps {
            get {
                return ResourceManager.GetString("Label_SocialApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string Label_Support {
            get {
                return ResourceManager.GetString("Label_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI / UX Design.
        /// </summary>
        internal static string Label_UIDesign {
            get {
                return ResourceManager.GetString("Label_UIDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        internal static string Label_Web {
            get {
                return ResourceManager.GetString("Label_Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Booklets for Belarusian exhibition company.&lt;/p&gt;.
        /// </summary>
        internal static string Projects_BelinterexpoDescription {
            get {
                return ResourceManager.GetString("Projects_BelinterexpoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Cargo Club - SaaS platform for logistics and transport companies.&lt;/p&gt;.
        /// </summary>
        internal static string Projects_CargoDescription {
            get {
                return ResourceManager.GetString("Projects_CargoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string Projects_Header {
            get {
                return ResourceManager.GetString("Projects_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here can be your project!.
        /// </summary>
        internal static string Projects_Proposal {
            get {
                return ResourceManager.GetString("Projects_Proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;VerniMoment - dating service for CIS market.&lt;/p&gt;.
        /// </summary>
        internal static string Projects_VerniMomentDescription {
            get {
                return ResourceManager.GetString("Projects_VerniMomentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch you project with an experienced team!.
        /// </summary>
        internal static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core team.
        /// </summary>
        internal static string Team_Header {
            get {
                return ResourceManager.GetString("Team_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Responsible for project management and customer relations.&lt;/p&gt;
        ///&lt;p&gt;More than 6 years in IT. Launched few own projects with total investments 200k$.&lt;/p&gt;
        ///&lt;p&gt;Projects were mentioned on Echo Moscow, AdWeek, Forbes, etc.&lt;/p&gt;
        ///&lt;p&gt;Finalist at New York 2012 July Seed Camp competition.&lt;/p&gt;.
        /// </summary>
        internal static string Team_Member1Description {
            get {
                return ResourceManager.GetString("Team_Member1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stanislav Bril.
        /// </summary>
        internal static string Team_Member1Name {
            get {
                return ResourceManager.GetString("Team_Member1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string Team_Member1Position {
            get {
                return ResourceManager.GetString("Team_Member1Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Responsible for UI and UX. More than 50 successfully delivered projects.&lt;/p&gt;
        ///&lt;p&gt;Experience in Web design as well as Mobile.&lt;/p&gt;
        ///&lt;p&gt;Promo graphic and print graphic design.&lt;/p&gt;.
        /// </summary>
        internal static string Team_Member2Description {
            get {
                return ResourceManager.GetString("Team_Member2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artiom Petrykin.
        /// </summary>
        internal static string Team_Member2Name {
            get {
                return ResourceManager.GetString("Team_Member2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art Director.
        /// </summary>
        internal static string Team_Member2Position {
            get {
                return ResourceManager.GetString("Team_Member2Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Responsible for development team. 5+ years of production experience in software development.&lt;/p&gt;
        ///&lt;p&gt;Skilled .NET, C#, JavaScript, SQL, ASP.NET developer.&lt;/p&gt;.
        /// </summary>
        internal static string Team_Member3Description {
            get {
                return ResourceManager.GetString("Team_Member3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alexander Kunavich.
        /// </summary>
        internal static string Team_Member3Name {
            get {
                return ResourceManager.GetString("Team_Member3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech Lead.
        /// </summary>
        internal static string Team_Member3Position {
            get {
                return ResourceManager.GetString("Team_Member3Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argo.
        /// </summary>
        internal static string Title_Index {
            get {
                return ResourceManager.GetString("Title_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string TopMenu_AboutUs {
            get {
                return ResourceManager.GetString("TopMenu_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string TopMenu_Company {
            get {
                return ResourceManager.GetString("TopMenu_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string TopMenu_Projects {
            get {
                return ResourceManager.GetString("TopMenu_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string TopMenu_Team {
            get {
                return ResourceManager.GetString("TopMenu_Team", resourceCulture);
            }
        }
    }
}
